from instruments.abstract_instruments.instrument import Instrument
from instruments.abstract_instruments.multimeter import Multimeter
from instruments.abstract_instruments.wrapperabc import WrapperABC
