version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

sphinx:
  builder: html
  configuration: doc/source/conf.py
  fail_on_warning: false

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
